[package]
name = "changelog-rs"
version = "0.3.0"
authors = ["Per Lundberg <perlun@gmail.com>"]
description = "Generates CHANGELOG.md files based on git commit and tag information."
license = "MIT"
homepage = "https://github.com/perlun/changelog-rs"

[dependencies]
semver = "0.5.0"
clap = "2"
